/* DO NOT EDIT. generate_boards.py v1; GPL-3.0-only
 * board+pin input SHA256: 64a30095ca4c56c4247c570ace69df4520cbbf1e74424cfd66e7a62abb984b40
 * Review board contract; not fabrication/vehicle approval. */
#ifndef CANVIEW_BOARD_PINS_H
#define CANVIEW_BOARD_PINS_H

#define CANVIEW_BOARD_ID "comm-r2-n16r8"
#define CANVIEW_BOARD_MODULE "ESP32-S3-WROOM-1-N16R8"
#define CANVIEW_BOARD_FLASH_BYTES (16777216U)
#define CANVIEW_BOARD_ESP_BOOT_N_GPIO (0U)
#define CANVIEW_BOARD_ESP_RTS_SRC_GPIO (15U)
#define CANVIEW_BOARD_ESP_RUN_OK_GPIO (7U)
#define CANVIEW_BOARD_ESP_TX_SRC_GPIO (17U)
#define CANVIEW_BOARD_GPS_PPS_GPIO (6U)
#define CANVIEW_BOARD_GPS_PWR_REQ_GPIO (47U)
#define CANVIEW_BOARD_GPS_RX_TAP_GPIO (5U)
#define CANVIEW_BOARD_GPS_TX_SELECT_GPIO (4U)
#define CANVIEW_BOARD_IMU_CS_N_GPIO (13U)
#define CANVIEW_BOARD_IMU_DRDY_GPIO (14U)
#define CANVIEW_BOARD_IMU_MISO_GPIO (12U)
#define CANVIEW_BOARD_IMU_MOSI_GPIO (11U)
#define CANVIEW_BOARD_IMU_RESET_N_GPIO (21U)
#define CANVIEW_BOARD_IMU_SCLK_GPIO (10U)
#define CANVIEW_BOARD_RECOVERY_BUTTON_N_GPIO (8U)
#define CANVIEW_BOARD_SERVICE_RUN_SENSE_GPIO (48U)
#define CANVIEW_BOARD_STM_BOOT0_REQ_GPIO (2U)
#define CANVIEW_BOARD_STM_RECOVERY_N_GPIO (9U)
#define CANVIEW_BOARD_STM_RESET_CMD_N_GPIO (1U)
#define CANVIEW_BOARD_STM_RTS_GPIO (16U)
#define CANVIEW_BOARD_STM_TX_GPIO (18U)
#define CANVIEW_BOARD_USB_DM_GPIO (19U)
#define CANVIEW_BOARD_USB_DP_GPIO (20U)
#define CANVIEW_BOARD_USB_SERVICE_SENSE_GPIO (38U)
#define CANVIEW_BOARD_PSRAM_BYTES (8388608U)
#define CANVIEW_BOARD_RECOVERY_GPIO (8U)

#endif
