/* SPDX-License-Identifier: GPL-3.0-only */
/** @file fdcan_message_ram.h
 * @brief STM32G4 fixed FDCAN Message RAM contract.
 *
 * STM32G4 does not expose the configurable RXF0C/RXESC registers used by
 * other M_CAN variants. The Message RAM regions and element sizes are fixed
 * by the STM32G4 integration. These constants mirror the official
 * STM32CubeG4 v1.6.3 HAL source and are checked against that source at target
 * post-build time.
 */
#ifndef CANVIEW_STM_FDCAN_MESSAGE_RAM_H
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_H

#include <stdint.h>

#define CANVIEW_STM_FDCAN_MESSAGE_RAM_STANDARD_FILTER_COUNT (28U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_COUNT (8U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_ELEMENT_COUNT (3U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_ELEMENT_COUNT (3U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_ELEMENT_COUNT (3U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_ELEMENT_COUNT (3U)

#define CANVIEW_STM_FDCAN_MESSAGE_RAM_STANDARD_FILTER_ELEMENT_BYTES (4U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_ELEMENT_BYTES (8U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_ELEMENT_BYTES (72U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_ELEMENT_BYTES (72U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_ELEMENT_BYTES (8U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_ELEMENT_BYTES (72U)

#define CANVIEW_STM_FDCAN_MESSAGE_RAM_STANDARD_FILTER_OFFSET_BYTES (0U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_OFFSET_BYTES (112U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_OFFSET_BYTES (176U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_OFFSET_BYTES (392U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_OFFSET_BYTES (608U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_OFFSET_BYTES (632U)
#define CANVIEW_STM_FDCAN_MESSAGE_RAM_INSTANCE_BYTES (848U)

typedef char canview_stm_fdcan_message_ram_layout_contract[
    (CANVIEW_STM_FDCAN_MESSAGE_RAM_STANDARD_FILTER_OFFSET_BYTES == 0U &&
     CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_OFFSET_BYTES ==
         CANVIEW_STM_FDCAN_MESSAGE_RAM_STANDARD_FILTER_COUNT *
             CANVIEW_STM_FDCAN_MESSAGE_RAM_STANDARD_FILTER_ELEMENT_BYTES &&
     CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_OFFSET_BYTES ==
         CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_OFFSET_BYTES +
             CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_COUNT *
                 CANVIEW_STM_FDCAN_MESSAGE_RAM_EXTENDED_FILTER_ELEMENT_BYTES &&
     CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_OFFSET_BYTES ==
         CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_OFFSET_BYTES +
             CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_ELEMENT_COUNT *
                 CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO0_ELEMENT_BYTES &&
     CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_OFFSET_BYTES ==
         CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_OFFSET_BYTES +
             CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_ELEMENT_COUNT *
                 CANVIEW_STM_FDCAN_MESSAGE_RAM_RX_FIFO1_ELEMENT_BYTES &&
     CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_OFFSET_BYTES ==
         CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_OFFSET_BYTES +
             CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_ELEMENT_COUNT *
                 CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_EVENT_FIFO_ELEMENT_BYTES &&
     CANVIEW_STM_FDCAN_MESSAGE_RAM_INSTANCE_BYTES ==
         CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_OFFSET_BYTES +
             CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_ELEMENT_COUNT *
                 CANVIEW_STM_FDCAN_MESSAGE_RAM_TX_FIFO_ELEMENT_BYTES)
        ? 1
        : -1];

#endif
