/* SPDX-License-Identifier: GPL-3.0-only */
#ifndef CANVIEW_BOOT_ASN1_CONFIG_H
#define CANVIEW_BOOT_ASN1_CONFIG_H
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_ASN1_PARSE_C
#endif
