/* DO NOT EDIT. generate_transport.py v1; SPDX-License-Identifier: GPL-3.0-only
 * source SHA256: 8acbc538b8a1a43dfb2eeedd10e07308a271a2af3886b5575bc81bd2ab1b1ab3
 * Envelope foundation only; not complete/authorized runtime ABI. */
#ifndef CANVIEW_WIRE_LAYOUT_H
#define CANVIEW_WIRE_LAYOUT_H
#include <stdint.h>

#define CANVIEW_WIRE_ESPNOW_MAGIC_OFFSET (0U)
#define CANVIEW_WIRE_ESPNOW_MAJOR_OFFSET (2U)
#define CANVIEW_WIRE_ESPNOW_MINOR_OFFSET (3U)
#define CANVIEW_WIRE_ESPNOW_HEADER_LEN_OFFSET (4U)
#define CANVIEW_WIRE_ESPNOW_MESSAGE_TYPE_OFFSET (5U)
#define CANVIEW_WIRE_ESPNOW_FLAGS_OFFSET (6U)
#define CANVIEW_WIRE_ESPNOW_PRIORITY_OFFSET (7U)
#define CANVIEW_WIRE_ESPNOW_SESSION_ID_OFFSET (8U)
#define CANVIEW_WIRE_ESPNOW_SEQUENCE_OFFSET (12U)
#define CANVIEW_WIRE_ESPNOW_SENDER_TIME_MS_OFFSET (16U)
#define CANVIEW_WIRE_ESPNOW_CORRELATION_ID_OFFSET (20U)
#define CANVIEW_WIRE_ESPNOW_PAYLOAD_LEN_OFFSET (24U)
#define CANVIEW_WIRE_ESPNOW_RESERVED_OFFSET (26U)
#define CANVIEW_WIRE_ESPNOW_CRC32_OFFSET (28U)
#define CANVIEW_WIRE_ESPNOW_MAJOR (1U)
#define CANVIEW_WIRE_ESPNOW_MINOR (3U)
#define CANVIEW_WIRE_ESPNOW_MAGIC (22083U)
#define CANVIEW_WIRE_ESPNOW_MAX_FRAME (240U)
#define CANVIEW_WIRE_ESPNOW_FLAGS_MASK (127U)
#define CANVIEW_WIRE_ESPNOW_HEADER_SIZE (32U)
#define CANVIEW_WIRE_ESPNOW_MAX_PAYLOAD (208U)
#define CANVIEW_WIRE_UART_MAGIC_OFFSET (0U)
#define CANVIEW_WIRE_UART_MAJOR_OFFSET (2U)
#define CANVIEW_WIRE_UART_MINOR_OFFSET (3U)
#define CANVIEW_WIRE_UART_MESSAGE_TYPE_OFFSET (4U)
#define CANVIEW_WIRE_UART_FLAGS_OFFSET (5U)
#define CANVIEW_WIRE_UART_HEADER_LEN_OFFSET (6U)
#define CANVIEW_WIRE_UART_PAYLOAD_LEN_OFFSET (8U)
#define CANVIEW_WIRE_UART_RESERVED_OFFSET (10U)
#define CANVIEW_WIRE_UART_SEQUENCE_OFFSET (12U)
#define CANVIEW_WIRE_UART_CORRELATION_ID_OFFSET (16U)
#define CANVIEW_WIRE_UART_SENDER_TIME_US_OFFSET (20U)
#define CANVIEW_WIRE_UART_CRC32_OFFSET (28U)
#define CANVIEW_WIRE_UART_MAJOR (1U)
#define CANVIEW_WIRE_UART_MINOR (0U)
#define CANVIEW_WIRE_UART_MAGIC (21827U)
#define CANVIEW_WIRE_UART_MAX_FRAME (1024U)
#define CANVIEW_WIRE_UART_FLAGS_MASK (31U)
#define CANVIEW_WIRE_UART_HEADER_SIZE (32U)
#define CANVIEW_WIRE_UART_MAX_PAYLOAD (992U)
#define CANVIEW_WIRE_UART_MAX_ENCODED (1029U)
#define CANVIEW_WIRE_UART_MAX_SERIAL (CANVIEW_WIRE_UART_MAX_ENCODED + 1U)
#define CANVIEW_WIRE_ESPNOW_MAX_PRIORITY (4U)
#define CANVIEW_WIRE_UART_BAUD (4000000U)
#define CANVIEW_WIRE_CAN_ESPNOW_MESSAGE (32U)
#define CANVIEW_WIRE_CAN_UART_MESSAGE (16U)
#define CANVIEW_WIRE_CAN_PREFIX_SIZE (12U)
#define CANVIEW_WIRE_CAN_RECORD_SIZE (16U)
#define CANVIEW_WIRE_CAN_MAX_RECORDS (12U)
#define CANVIEW_WIRE_CAN_BUS_COUNT (3U)
#define CANVIEW_WIRE_CAN_MAX_DLC (8U)
#define CANVIEW_WIRE_CAN_STANDARD_ID_MAX (2047U)
#define CANVIEW_WIRE_CAN_EXTENDED_ID_MAX (536870911U)
#define CANVIEW_WIRE_CRC_POLYNOMIAL_REFLECTED UINT32_C(0xEDB88320)
#define CANVIEW_WIRE_CRC_INITIAL UINT32_C(0xFFFFFFFF)
#define CANVIEW_WIRE_CRC_XOR_OUT UINT32_C(0xFFFFFFFF)
#define CANVIEW_WIRE_CRC_CHECK_123456789 UINT32_C(0xCBF43926)

/* C99 compile-time contracts; never sizeof(host_struct) as wire ABI. */
typedef char canview_assert_byte_width[(UINT8_MAX == 255U) ? 1 : -1];
typedef char canview_assert_can_fits[((CANVIEW_WIRE_CAN_PREFIX_SIZE +
    CANVIEW_WIRE_CAN_MAX_RECORDS * CANVIEW_WIRE_CAN_RECORD_SIZE) <=
    CANVIEW_WIRE_ESPNOW_MAX_PAYLOAD) ? 1 : -1];

#endif
