#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdlib.h>

#define LV_COLOR_DEPTH 32
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (4U * 1024U * 1024U)
#define LV_USE_USER_DATA 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_STYLE 1
#define LV_USE_ASSERT_OBJ 1
#define LV_USE_ASSERT_MEM_INTEGRITY 1
#define LV_ASSERT_HANDLER abort();
#define LV_USE_LOG 0
#define LV_USE_THEME_DEFAULT 0
#define LV_USE_THEME_BASIC 0
#define LV_USE_THEME_MONO 0
#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR 0

#endif
