"""Diagnostic Bridge의 재현 가능한 gzip HTML asset을 C 배열로 생성한다."""
from __future__ import annotations

import argparse
import gzip
from pathlib import Path


def c_array(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        rows.append("    " + ", ".join(f"0x{value:02X}" for value in data[offset:offset + 12]) + ",")
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    source = args.input.read_bytes()
    compressed = gzip.compress(source, compresslevel=9, mtime=0)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    header = """/* DO NOT EDIT. Generated by generate_bridge_web_assets.py. */
#ifndef CANVIEW_BRIDGE_ASSETS_H
#define CANVIEW_BRIDGE_ASSETS_H
#include <stddef.h>
#include <stdint.h>
extern const uint8_t canview_bridge_index_html_gz[];
extern const size_t canview_bridge_index_html_gz_len;
#endif
"""
    source_text = f"""/* DO NOT EDIT. Generated by generate_bridge_web_assets.py. */
#include <stddef.h>
#include <stdint.h>
#include \"bridge_assets.h\"
const uint8_t canview_bridge_index_html_gz[] = {{
{c_array(compressed)}
}};
const size_t canview_bridge_index_html_gz_len = sizeof(canview_bridge_index_html_gz);
"""
    (args.output_dir / "bridge_assets.h").write_text(header, encoding="utf-8", newline="\n")
    (args.output_dir / "bridge_assets.c").write_text(source_text, encoding="utf-8", newline="\n")
    print(f"PASS: bridge asset {len(source)} bytes -> {len(compressed)} gzip bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
