/* DO NOT EDIT. generate_boards.py v1; GPL-3.0-only
 * board+pin input SHA256: 5c4483042bd4a94d64eb7efcc5cf9cdfa3b0bff464e9bc9b5831751de1791e57
 * Review board contract; not fabrication/vehicle approval. */
#ifndef CANVIEW_BOARD_PINS_H
#define CANVIEW_BOARD_PINS_H

#define CANVIEW_BOARD_ID "controller-waveshare35-adapter-r1_1"
#define CANVIEW_BOARD_MODULE "ESP32-S3R8"
#define CANVIEW_BOARD_FLASH_BYTES (16777216U)
#define CANVIEW_BOARD_WIDTH (320U)
#define CANVIEW_BOARD_HEIGHT (480U)
#define CANVIEW_BOARD_HZ (400000U)
#define CANVIEW_BOARD_RTC_ADDRESS (81U)
#define CANVIEW_BOARD_IO_EXPANDER_ADDRESS (32U)
#define CANVIEW_BOARD_DEBUG_RX_GPIO (44U)
#define CANVIEW_BOARD_DEBUG_TX_GPIO (43U)
#define CANVIEW_BOARD_I2C_SCL_GPIO (7U)
#define CANVIEW_BOARD_I2C_SDA_GPIO (8U)
#define CANVIEW_BOARD_I2S_BCLK_GPIO (13U)
#define CANVIEW_BOARD_I2S_MCLK_GPIO (12U)
#define CANVIEW_BOARD_I2S_PLAY_DATA_GPIO (16U)
#define CANVIEW_BOARD_I2S_REC_DATA_GPIO (14U)
#define CANVIEW_BOARD_I2S_WS_GPIO (15U)
#define CANVIEW_BOARD_LCD_BL_GPIO (6U)
#define CANVIEW_BOARD_LCD_DC_GPIO (3U)
#define CANVIEW_BOARD_LCD_MISO_GPIO (2U)
#define CANVIEW_BOARD_LCD_MOSI_GPIO (1U)
#define CANVIEW_BOARD_LCD_SCLK_GPIO (5U)
#define CANVIEW_BOARD_MIC_BCLK_GPIO (38U)
#define CANVIEW_BOARD_MIC_SD_GPIO (40U)
#define CANVIEW_BOARD_MIC_WS_GPIO (39U)
#define CANVIEW_BOARD_RECOVERY_BUTTON_N_GPIO (41U)
#define CANVIEW_BOARD_USB_DM_GPIO (19U)
#define CANVIEW_BOARD_USB_DP_GPIO (20U)
#define CANVIEW_BOARD_PSRAM_BYTES (8388608U)
#define CANVIEW_BOARD_RECOVERY_GPIO (41U)

#endif
