/* SPDX-License-Identifier: GPL-3.0-only */
#ifndef CANVIEW_BOARD_PINS_H
#define CANVIEW_BOARD_PINS_H

#define CANVIEW_BOARD_CAN1_RX_PORT (0U)
#define CANVIEW_BOARD_CAN1_RX_PIN (11U)
#define CANVIEW_BOARD_CAN1_TX_REQ_PORT (0U)
#define CANVIEW_BOARD_CAN1_TX_REQ_PIN (12U)
#define CANVIEW_BOARD_CAN2_RX_PORT (1U)
#define CANVIEW_BOARD_CAN2_RX_PIN (12U)
#define CANVIEW_BOARD_CAN2_TX_REQ_PORT (1U)
#define CANVIEW_BOARD_CAN2_TX_REQ_PIN (13U)
#define CANVIEW_BOARD_CAN3_RX_PORT (0U)
#define CANVIEW_BOARD_CAN3_RX_PIN (8U)
#define CANVIEW_BOARD_CAN3_TX_REQ_PORT (0U)
#define CANVIEW_BOARD_CAN3_TX_REQ_PIN (15U)
#define CANVIEW_BOARD_FT_EN_REQ_PORT (0U)
#define CANVIEW_BOARD_FT_EN_REQ_PIN (6U)
#define CANVIEW_BOARD_STB1_REQ_PORT (0U)
#define CANVIEW_BOARD_STB1_REQ_PIN (4U)
#define CANVIEW_BOARD_STB2_REQ_PORT (0U)
#define CANVIEW_BOARD_STB2_REQ_PIN (5U)

#define CANVIEW_BOARD_ESP_RTS_PORT (0U)
#define CANVIEW_BOARD_ESP_RTS_PIN (0U)
#define CANVIEW_BOARD_STM_RTS_SRC_PORT (0U)
#define CANVIEW_BOARD_STM_RTS_SRC_PIN (1U)
#define CANVIEW_BOARD_STM_TX_SRC_PORT (0U)
#define CANVIEW_BOARD_STM_TX_SRC_PIN (2U)
#define CANVIEW_BOARD_ESP_TX_PORT (0U)
#define CANVIEW_BOARD_ESP_TX_PIN (3U)

#define CANVIEW_BOARD_HSE_HZ (16000000U)
#define CANVIEW_BOARD_PLL_M (4U)
#define CANVIEW_BOARD_PLL_N (80U)
#define CANVIEW_BOARD_PLL_R (2U)
#define CANVIEW_BOARD_PLL_Q (4U)
#define CANVIEW_BOARD_PCLK1_HZ (80000000U)
#define CANVIEW_BOARD_FDCAN_HZ (80000000U)
#define CANVIEW_BOARD_UART_BAUD (4000000U)
#define CANVIEW_BOARD_UART_BRR (20U)

#endif
