/* SPDX-License-Identifier: GPL-3.0-only */
#ifndef CANVIEW_TEST_STM32G4XX_LL_DMAMUX_H
#define CANVIEW_TEST_STM32G4XX_LL_DMAMUX_H

#define LL_DMAMUX_REQ_USART2_RX (7U)
#define LL_DMAMUX_REQ_USART2_TX (8U)

#endif
